### ISSUE TITLE
kaiju 1.7.0 renamed mkbwt to kaiju-mkbwt

### ISSUE THREAD

**Issue by peterjc** [abaizan/kodoja#37]
Today's build failed https://travis-ci.org/abaizan/kodoja/builds/572680971 (updated a README only) on Python 3.6 with floating dependencies:

```
Which version of Python do we have?
Python 3.6.9 :: Anaconda, Inc.
Do we have ncbi-genome-download?
0.2.10
Do we have kraken?
Kraken version 1.1.1
Copyright 2013-2019, Derrick Wood, Jennifer Lu (jlu26@jhmi.edu))
Do we have kaiju?
Kaiju 1.7.2
Do we have trimmomatic?
0.39
Do we have fastqc?
FastQC v0.11.8
Do we have numpy?
1.17.0
Do we have pandas?
0.25.0
Do we have biopython?
1.74
```

```
/bin/sh: 1: mkbwt: not found
Kodoja failed unexpectedly with the following:
Traceback (most recent call last):
  File "diagnosticTool_scripts/kodoja_build.py", line 168, in <module>
    main()
  File "diagnosticTool_scripts/kodoja_build.py", line 159, in main
    kaijuDB_build(args.output_dir, kaiju_db_dir, subset_vir_assembly)
  File "/home/travis/build/abaizan/kodoja/diagnosticTool_scripts/database_modules.py", line 236, in kaijuDB_build
    shell=True)
  File "/home/travis/miniconda/envs/snowflakes/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mkbwt -n 5 -a ACDEFGHIKLMNPQRSTVWY -o test/building_db/kaijuDB_test/kaiju_library test/building_db/kaijuDB_test/kaiju_library.faa' returned non-zero exit status 127.
```

The matching build with Python 3.6 and pinned dependencies worked.

```
Which version of Python do we have?
Python 3.6.9 :: Anaconda, Inc.
Do we have ncbi-genome-download?
0.2.6
Do we have kraken?
Kraken version 1.0
Copyright 2013-2015, Derrick Wood (dwood@cs.jhu.edu)
Do we have kaiju?
Kaiju 1.5.0
Do we have trimmomatic?
0.36
Do we have fastqc?
FastQC v0.11.5
Do we have numpy?
1.9.0
Do we have pandas?
/home/travis/miniconda/envs/snowflakes/lib/python3.6/site-packages/pandas/io/excel.py:626: UserWarning: Installed openpyxl is not supported at this time. Use >=1.6.1 and <2.0.0.
  .format(openpyxl_compat.start_ver, openpyxl_compat.stop_ver))
0.14.0
Do we have biopython?
1.67
```

The previous build with floating versions also worked, https://travis-ci.org/abaizan/kodoja/jobs/487385399

```
Which version of Python do we have?
Python 3.6.8 :: Anaconda, Inc.
Do we have ncbi-genome-download?
0.2.9
Do we have kraken?
Kraken version 1.0
Copyright 2013-2015, Derrick Wood (dwood@cs.jhu.edu)
Do we have kaiju?
Kaiju 1.6.3
Do we have trimmomatic?
0.38
Do we have fastqc?
FastQC v0.11.8
Do we have numpy?
1.16.1
Do we have pandas?
0.24.0
Do we have biopython?
1.73
```

This looks like a change in Kaiju from 1.5.0 and 1.6.3 (working) to 1.7.2 (broken)

**Comment by peterjc** [comment]
kaiju 1.7.0 renamed their internal tools, in this case ``mkbwt`` to ``kaiju-mkbwt``

https://github.com/bioinformatics-centre/kaiju/commit/4a628c9643f1cddad2b79454634e48f734a0bd5c

Simplest fix is to pin to an older version... more practically we might cope with either.
