### ISSUE TITLE
PE test fails, pandas ValueError: could not convert string to float: '100/1'

### ISSUE THREAD

**Issue by peterjc** [abaizan/kodoja#4]
Despite some pain along the way, I have got the Galaxy wrapper far enough along to run the tests via ``planemo test kodoja_search.xml`` locally and on TravisCI.

e.g. https://travis-ci.org/peterjc/kodoja_galaxy/jobs/339418928

This worked for the single end test, but the paired end tests fail:

```
|  Traceback (most recent call last):
|  File "/home/travis/miniconda3/envs/__kodoja_unver/bin/kodoja_search.py", line 120, in <module>
|  args.data_format, kraken_file1, args.host_subset, kraken_file2)
|  File "/home/travis/miniconda3/envs/__kodoja_unver/bin/diagnostic_modules.py", line 263, in seq_reanalysis
|  kraken_fullTable['Seq_ID'] = kraken_fullTable['Seq_ID'].astype(float)
|  File "/home/travis/miniconda3/envs/__kodoja_unver/lib/python3.5/site-packages/pandas/util/_decorators.py", line 118, in wrapper
|  return func(*args, **kwargs)
|  File "/home/travis/miniconda3/envs/__kodoja_unver/lib/python3.5/site-packages/pandas/core/generic.py", line 4004, in astype
|  **kwargs)
|  File "/home/travis/miniconda3/envs/__kodoja_unver/lib/python3.5/site-packages/pandas/core/internals.py", line 3462, in astype
|  return self.apply('astype', dtype=dtype, **kwargs)
|  File "/home/travis/miniconda3/envs/__kodoja_unver/lib/python3.5/site-packages/pandas/core/internals.py", line 3329, in apply
|  applied = getattr(b, f)(**kwargs)
|  File "/home/travis/miniconda3/envs/__kodoja_unver/lib/python3.5/site-packages/pandas/core/internals.py", line 544, in astype
|  **kwargs)
|  File "/home/travis/miniconda3/envs/__kodoja_unver/lib/python3.5/site-packages/pandas/core/internals.py", line 625, in _astype
|  values = astype_nansafe(values.ravel(), dtype, copy=True)
|  File "/home/travis/miniconda3/envs/__kodoja_unver/lib/python3.5/site-packages/pandas/core/dtypes/cast.py", line 703, in astype_nansafe
|  return arr.astype(dtype)
|  ValueError: could not convert string to float: '100/1'
```

Frustratingly being based on the current kodoja test cases, this example works outside of Galaxy/planemo. My hunches are a subtle Python 2 vs 3 issue, or a differences in the pandas version?

Any thoughts?

**Comment by peterjc** [comment]
I can get this to fail now outside of Galaxy/Planemo, not sure what has changed.

Using the trivial patch on #5 which adds more logging to the test script, but otherwise the master branch (updates since v0.0.2) gives the following with my self-compiled Python 3.5,

```
$ test/test_script.sh 
Which version of Python do we have?
Python 3.5.0
Do we have ncbi-genome-download?
0.2.5
Do we have kraken?
Kraken version 1.0
Copyright 2013-2015, Derrick Wood (dwood@cs.jhu.edu)
Do we have kaiju?
Kaiju 1.5.0
Do we have trimmomatic?
0.36
Do we have fastqc?
FastQC v0.11.6
Do we have numpy?
1.12.1
Do we have pandas?
0.19.2
Do we have biopython?
1.71.dev0
Beginning tests...
...
==============================================================
Testing kodoja_search.py with paired end FASTQ
==============================================================
TrimmomaticPE: Started with arguments:
 -threads 2 test/PE_test/renamed_file_1.fastq test/PE_test/renamed_file_2.fastq test/PE_test/trimmed_read1 test/PE_test/PE_trimmed_data_1U test/PE_test/trimmed_read2 test/PE_test/PE_trimmed_data_2U LEADING:20 TRAILING:20 MINLEN:50
Quality encoding detected as phred33
Input Read Pairs: 100 Both Surviving: 94 (94.00%) Forward Only Surviving: 3 (3.00%) Reverse Only Surviving: 2 (2.00%) Dropped: 1 (1.00%)
TrimmomaticPE: Completed successfully
Started analysis of trimmed_read1
Analysis complete for trimmed_read1
Started analysis of trimmed_read2
Analysis complete for trimmed_read2
94 sequences (0.02 Mbp) processed in 0.046s (122.8 Kseq/m, 24.87 Mbp/m).
  94 sequences classified (100.00%)
  0 sequences unclassified (0.00%)
Traceback (most recent call last):
  File "diagnosticTool_scripts/kodoja_search.py", line 120, in <module>
    args.data_format, kraken_file1, kraken_file2)
  File "/mnt/shared/users/xxx/repositories/kodoja/diagnosticTool_scripts/diagnostic_modules.py", line 263, in seq_reanalysis
    kraken_fullTable['Seq_ID'] = kraken_fullTable['Seq_ID'].astype(float)
  File "/home/xxx/lib/python3.5/site-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/home/xxx/lib/python3.5/site-packages/pandas/core/internals.py", line 3189, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/home/xxx/lib/python3.5/site-packages/pandas/core/internals.py", line 3056, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/xxx/lib/python3.5/site-packages/pandas/core/internals.py", line 461, in astype
    values=values, **kwargs)
  File "/home/xxx/lib/python3.5/site-packages/pandas/core/internals.py", line 504, in _astype
    values = _astype_nansafe(values.ravel(), dtype, copy=True)
  File "/home/xxx/lib/python3.5/site-packages/pandas/types/cast.py", line 537, in _astype_nansafe
    return arr.astype(dtype)
ValueError: could not convert string to float: '100/1'
```

Using v0.0.2 with the logging patches seems to give the same, so the recent changes are unrelated.

Using the master with the logging patches and the conda Python 3.6 gives the same:

```
$ PATH=/mnt/shared/scratch/synology/xxx/apps/conda/bin/:/bin:/usr/bin:/usr/local/sbin:/usr/sbin test/test_script.sh 
Which version of Python do we have?
Python 3.6.3
Do we have ncbi-genome-download?
0.2.5
Do we have kraken?
Kraken version 1.0
Copyright 2013-2015, Derrick Wood (dwood@cs.jhu.edu)
Do we have kaiju?
Kaiju 1.5.0
Do we have trimmomatic?
0.36
Do we have fastqc?
FastQC v0.11.6
Do we have numpy?
1.14.0
Do we have pandas?
0.22.0
Do we have biopython?
1.70
Beginning tests...
...
==============================================================
Testing kodoja_search.py with paired end FASTQ
==============================================================
TrimmomaticPE: Started with arguments:
 -threads 2 test/PE_test/renamed_file_1.fastq test/PE_test/renamed_file_2.fastq test/PE_test/trimmed_read1 test/PE_test/PE_trimmed_data_1U test/PE_test/trimmed_read2 test/PE_test/PE_trimmed_data_2U LEADING:20 TRAILING:20 MINLEN:50
Quality encoding detected as phred33
Input Read Pairs: 100 Both Surviving: 94 (94.00%) Forward Only Surviving: 3 (3.00%) Reverse Only Surviving: 2 (2.00%) Dropped: 1 (1.00%)
TrimmomaticPE: Completed successfully
Started analysis of trimmed_read1
Analysis complete for trimmed_read1
Started analysis of trimmed_read2
Analysis complete for trimmed_read2
94 sequences (0.02 Mbp) processed in 0.041s (138.6 Kseq/m, 28.06 Mbp/m).
  94 sequences classified (100.00%)
  0 sequences unclassified (0.00%)
Traceback (most recent call last):
  File "diagnosticTool_scripts/kodoja_search.py", line 120, in <module>
    args.data_format, kraken_file1, kraken_file2)
  File "/mnt/shared/users/xxx/repositories/kodoja/diagnosticTool_scripts/diagnostic_modules.py", line 263, in seq_reanalysis
    kraken_fullTable['Seq_ID'] = kraken_fullTable['Seq_ID'].astype(float)
  File "/mnt/shared/scratch/synology/xxx/apps/conda/lib/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/mnt/shared/scratch/synology/xxx/apps/conda/lib/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/mnt/shared/scratch/synology/xxx/apps/conda/lib/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/mnt/shared/scratch/synology/xxx/apps/conda/lib/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/mnt/shared/scratch/synology/xxx/apps/conda/lib/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/mnt/shared/scratch/synology/xxx/apps/conda/lib/python3.6/site-packages/pandas/core/internals.py", line 625, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "/mnt/shared/scratch/synology/xxx/apps/conda/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 703, in astype_nansafe
    return arr.astype(dtype)
ValueError: could not convert string to float: '100/1'
```

I'm a little confused right now, as I thought this was working locally at the end of last week.

**Comment by peterjc** [comment]
And another local failure, using a self-compiled Python 2.7 with slightly older Python libraries:

```
$ PATH=$HOME/bin:/mnt/shared/scratch/synology/xxx/apps/conda/bin/:/bin:/usr/bin:/usr/local/sbin:/usr/sbin test/test_script.sh 
Which version of Python do we have?
Python 2.7.10
Do we have ncbi-genome-download?
0.2.5
Do we have kraken?
Kraken version 1.0
Copyright 2013-2015, Derrick Wood (dwood@cs.jhu.edu)
Do we have kaiju?
Kaiju 1.5.0
Do we have trimmomatic?
0.36
Do we have fastqc?
FastQC v0.11.6
Do we have numpy?
1.11.0
Do we have pandas?
0.18.0
Do we have biopython?
1.71.dev0
Beginning tests...
...
==============================================================
Testing kodoja_search.py with paired end FASTQ
==============================================================
TrimmomaticPE: Started with arguments:
 -threads 2 test/PE_test/renamed_file_1.fastq test/PE_test/renamed_file_2.fastq test/PE_test/trimmed_read1 test/PE_test/PE_trimmed_data_1U test/PE_test/trimmed_read2 test/PE_test/PE_trimmed_data_2U LEADING:20 TRAILING:20 MINLEN:50
Quality encoding detected as phred33
Input Read Pairs: 100 Both Surviving: 94 (94.00%) Forward Only Surviving: 3 (3.00%) Reverse Only Surviving: 2 (2.00%) Dropped: 1 (1.00%)
TrimmomaticPE: Completed successfully
Started analysis of trimmed_read1
Analysis complete for trimmed_read1
Started analysis of trimmed_read2
Analysis complete for trimmed_read2
94 sequences (0.02 Mbp) processed in 0.040s (141.0 Kseq/m, 28.53 Mbp/m).
  94 sequences classified (100.00%)
  0 sequences unclassified (0.00%)
Traceback (most recent call last):
  File "diagnosticTool_scripts/kodoja_search.py", line 120, in <module>
    args.data_format, kraken_file1, kraken_file2)
  File "/mnt/shared/users/xxx/repositories/kodoja/diagnosticTool_scripts/diagnostic_modules.py", line 263, in seq_reanalysis
    kraken_fullTable['Seq_ID'] = kraken_fullTable['Seq_ID'].astype(float)
  File "/home/xxx/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/core/generic.py", line 2947, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/home/xxx/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/core/internals.py", line 2873, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/home/xxx/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/core/internals.py", line 2832, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/xxx/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/core/internals.py", line 422, in astype
    values=values, **kwargs)
  File "/home/xxx/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/core/internals.py", line 465, in _astype
    values = com._astype_nansafe(values.ravel(), dtype, copy=True)
  File "/home/xxx/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/core/common.py", line 2631, in _astype_nansafe
    return arr.astype(dtype)
ValueError: invalid literal for float(): 100/1
```

**Comment by peterjc** [comment]
I've started tracing the code, at it looks like the *N* paired input reads would have been renamed to ``1/1`` ... ``N/1`` and ``1/2`` ... ``N/2`` at this point, and that therefore the ``/1`` or ``/2`` suffix ought to be present - but it will of course break if turning this directly into the plain integer ``N`` by casting.

**Comment by peterjc** [comment]
OK, going back to the TravisCI results, v0.0.2 passed, under both Python 2.7 and 3.6:
https://travis-ci.org/abaizan/kodoja/builds/331761817

Focusing on that working Python 2.7 build,

```
$ conda install trimmomatic=0.36
$ conda install kraken=1.0
$ conda install fastqc=0.11.5
$ conda install kaiju=1.5.0
$ pip install numpy pandas biopython ncbi-genome-download
Collecting numpy
  Downloading numpy-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl (16.9MB)
    100% |████████████████████████████████| 16.9MB 65kB/s 
Collecting pandas
  Downloading pandas-0.22.0-cp27-cp27mu-manylinux1_x86_64.whl (24.3MB)
    100% |████████████████████████████████| 24.3MB 47kB/s 
Collecting biopython
  Downloading biopython-1.70-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 499kB/s 
Collecting ncbi-genome-download
  Downloading ncbi_genome_download-0.2.5-py2.py3-none-any.whl
...
```

Locally I also had ``trimmomatic=0.36`` and ncbi-genome-download 0.2.5.
Locally I had ``fastqc=0.11.6``, so I downgraded. Still broken.
Locally I had numpy ``1.11.0``, so I upgraded to ``1.14.0``. Still broken.
Locally I had biopython ``1.71.dev0`` (a pre-release), so I downgraded to 1.70. Still broken.
Locally I had pandas ``0.18.0``, so I upgraded to ``0.22.0``. Still broken.

That seems to rule out a version change in the main dependencies. I remain puzzled.
