### ISSUE TITLE
kodoja_build issue

### ISSUE THREAD

**Issue by codespacebyaditya** [abaizan/kodoja#43]
Tried building a kodoja database but ran into this error- 

Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/taxonomy/accession2taxid ... done.
==> SIZE nucl_est.accession2taxid.gz ... done.

==> PASV ... done.    ==> RETR nucl_est.accession2taxid.gz ...
No such file ‘nucl_est.accession2taxid.gz’.

Kodoja failed unexpectedly with the following:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/kodoja_build.py", line 168, in <module>
    main()
  File "/home/ubuntu/anaconda3/bin/kodoja_build.py", line 137, in main
    krakenDB_build(args.output_dir, kraken_db_dir, args.threads, args.kraken_kmer,
  File "/home/ubuntu/anaconda3/bin/database_modules.py", line 155, in krakenDB_build
    subprocess.check_call("kraken-build --download-taxonomy --threads " +
  File "/home/ubuntu/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'kraken-build --download-taxonomy --threads 1 --db ./krakenDB/' returned non-zero exit status 8.

**Comment by peterjc** [comment]
That looks like an issue within ``kraken-build``, can you check what version of kraken you have installed?
